// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (source, type, status, title, message, data)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, source, type, status, title, message, data, created_at
`

type CreateEventParams struct {
	Source  string         `json:"source"`
	Type    string         `json:"type"`
	Status  string         `json:"status"`
	Title   string         `json:"title"`
	Message string         `json:"message"`
	Data    sql.NullString `json:"data"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, createEvent,
		arg.Source,
		arg.Type,
		arg.Status,
		arg.Title,
		arg.Message,
		arg.Data,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.Type,
		&i.Status,
		&i.Title,
		&i.Message,
		&i.Data,
		&i.CreatedAt,
	)
	return i, err
}
