// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
	"time"
)

type Event struct {
	ID        int64          `json:"id"`
	Source    string         `json:"source"`
	Type      string         `json:"type"`
	Status    string         `json:"status"`
	Title     string         `json:"title"`
	Message   string         `json:"message"`
	Data      sql.NullString `json:"data"`
	CreatedAt time.Time      `json:"created_at"`
}
